# Generated by Django 2.2.2 on 2019-07-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gainsight', models.BooleanField(default=False)),
                ('outcome_data', models.CharField(max_length=255)),
                ('scorecard_history', models.CharField(max_length=255)),
                ('account_details', models.CharField(max_length=255)),
                ('preprocessed_file', models.CharField(max_length=255)),
                ('id_field', models.CharField(max_length=64)),
                ('churn_date', models.CharField(max_length=64)),
                ('snapshot_date', models.CharField(max_length=64)),
            ],
        ),
    ]
