# Generated by Django 2.2.2 on 2019-07-06 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='churn_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='run',
            name='snapshot_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
